AudioBooks/AudioBooks.Web/Controllers/AuthorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace AudioBooks.Web.Controllers
{
    [Authorize]
    public class AuthorController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public AuthorController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory ??
                throw new ArgumentNullException(nameof(httpClientFactory));
        }

        [HttpGet]
        public ActionResult AddAuthor()
        {
            return View("AddAuthor");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddAuthor(Model.LookupItemModel author)
        {
            if (ModelState.IsValid)
            {
                var httpClient = _httpClientFactory.CreateClient(Constants.APIClientNames.AudioBooksAPIClient);
                var request = new HttpRequestMessage(HttpMethod.Post, "/api/lookupdata/addauthor");
                request.Content = new StringContent(JsonConvert.SerializeObject(author), System.Text.Encoding.UTF8, "application/json");
                var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false);

                response.EnsureSuccessStatusCode();

                return RedirectToAction("Index", "Lookup");
            }
            else
            {
                return View("AddAuthor", author);
            }
        }

 

        [HttpGet]
        public ActionResult EditAuthor(int id, string name, string description)
        {
            if (id == 0)
            {
                return RedirectToAction("AddAuthor");
            }
            else
            {
                return View("EditAuthor", new Model.LookupItemModel { Id = id, Name = name, Description = description });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateAuthor(Model.LookupItemModel author)
        {
            if (ModelState.IsValid)
            {
                var httpClient = _httpClientFactory.CreateClient(Constants.APIClientNames.AudioBooksAPIClient);
                var request = new HttpRequestMessage(HttpMethod.Post, "/api/lookupdata/updateauthor");
                request.Content = new StringContent(JsonConvert.SerializeObject(author), System.Text.Encoding.UTF8, "application/json");
                var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false);

                response.EnsureSuccessStatusCode();

                return RedirectToAction("Index", "Lookup");
            }
            else
            {
                return View("EditAuthor", author);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAuthor(int id)
        {
            if (id > 0)
            {
                var httpClient = _httpClientFactory.CreateClient(Constants.APIClientNames.AudioBooksAPIClient);
                var request = new HttpRequestMessage(HttpMethod.Delete, $"/api/lookupdata/deleteauthor/{id}");                 
                //request.Content = new StringContent(JsonConvert.SerializeObject(new { id }), System.Text.Encoding.UTF8, "application/json");
                var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false);
                response.EnsureSuccessStatusCode();  
            }
            return RedirectToAction("Index", "Lookup");
        }

    }
}

AudioBooks/AudioBooks.Web/Controllers/LookupController.cs
using AudioBooks.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;

namespace AudioBooks.Web.Controllers
{
    [Authorize]
    public class LookupController : Controller
    {
 
        private readonly IHttpClientFactory _httpClientFactory;

        public LookupController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory ??
                throw new ArgumentNullException(nameof(httpClientFactory));
        }

        public async Task<IActionResult> Index()
        {  
            var httpClient = _httpClientFactory.CreateClient(Constants.APIClientNames.AudioBooksAPIClient);
            var request = new HttpRequestMessage(HttpMethod.Get, "/api/lookupdata");
            var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead);//.ConfigureAwait(false);// not needed for code .net core 

            response.EnsureSuccessStatusCode();

            using (var responseStream = await response.Content.ReadAsStreamAsync())
            {
                var model = await JsonSerializer.DeserializeAsync<Model.LookupDataCacheModel>(responseStream);
                var viewModel = new LookupDataCacheViewModel(model);
                return View(viewModel);
            }
        }

     
    }
}

AudioBooks/AudioBooks.Web/Views/Lookup/Index.cshtml
@model LookupDataCacheViewModel

@{
    ViewData["Title"] = "Lookup data";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<style>
    .section {
        margin-bottom: 10px;
    }
</style>
<div>
    <h2>Authors</h2>
    <div class="row  ">
        @{
            await Html.RenderPartialAsync("_LookupItem", Model.DataModel.Authors);
        }
    </div>
    <div>
        @using (Html.BeginForm("AddAuthor", "Lookup"))
        {
            <div class="button-container row">
                <div class=" ">
                    <a class="btn btn-primary" asp-controller="Author" asp-action="AddAuthor"><i class="fa fa-plus"></i> Add New</a>
                </div>
            </div>
        }
    </div>
</div>
<div>
    <h2>Categories</h2>
    <div class="row  ">
        @{
            await Html.RenderPartialAsync("_LookupItem", Model.DataModel.Catgegories);
        }
    </div>
    @using (Html.BeginForm("AddCategory", "Lookup"))
    {
        <div class="button-container row">
            <div class=" ">
                <button type="submit" class="btn btn-primary "><i class="fa fa-plus"></i> Add New</button>
            </div>
        </div>
    }
</div>

<div class="section">
    <h2>Publishers</h2>
    <div class="row  ">
        @{
            await Html.RenderPartialAsync("_LookupItem", Model.DataModel.Publishers);
        }
    </div>
    @using (Html.BeginForm("AddPublisher", "Lookup"))
    {
        <div class="button-container row">
            <div class="">
                <button type="submit" class="btn btn-primary "><i class="fa fa-plus"></i> Add New</button>
            </div>
        </div>
    }
</div>

AudioBooks/AudioBooks.Web/Views/Lookup/_LookupItem.cshtml
@model IEnumerable<AudioBooks.Model.LookupItemModel>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RecordOwnerId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RecordOwnerId)
            </td>
            <td>

                @Html.ActionLink("Edit", "EditAuthor", "Author",
               new { id = item.Id, name = item.Name, description = item.Description },
               new { @class = "btn btn-outline-info" })

                |

                @using (Html.BeginForm("DeleteAuthor", "Author", FormMethod.Post))
                {
                    @Html.AntiForgeryToken() 
                    <input type="hidden" id="id" name="id" value="@item.Id">

                    <div class="button-container row">
                        <div class=" ">
                            <button type="submit" class="btn btn-outline-warning"><i class="fa fa-cross"></i> Delete</button>
                        </div>
                    </div>
                }

            </td>
        </tr>
        }
    </tbody>
</table>
